{{- $_ := required "secretManager.existingSecretName is required" .Values.secretManager.existingSecretName -}}
{{- $_ := required "firewall.existingCaSecretName is required" .Values.firewall.existingCaSecretName -}}
{{- $_ := required "firewall.existingCaKeySecretName is required" .Values.firewall.existingCaKeySecretName -}}
{{- if .Values.postgres.enabled -}}
{{- $_ := required "postgres.auth.existingSecretName is required when postgres.enabled=true" .Values.postgres.auth.existingSecretName -}}
{{- $_ := required "postgres.auth.existingSecretKey is required when postgres.enabled=true" .Values.postgres.auth.existingSecretKey -}}
{{- end -}}
