import { createHash } from 'node:crypto';
import {
  displayPath,
  fileChangeFromToolCall,
  type AmpAssistantEvent,
  type AmpRawEvent,
  type AmpToolEvent,
  type AnthropicToolUseBlock,
  type CentaurEventFrame,
  type CodexItem,
  type JsonObject,
  type JsonValue,
  type QuestionPrompt,
  type ToolCallItem,
} from '@atrium/centaur-client';
import { isTerminalExecutionStatus } from '@atrium/centaur-client';
import type { Db, DbClient } from './db.js';
import { withTx } from './db.js';
import { stripSteerContextPrefix, type ParsedSteerContextBlock } from './steer-context.js';

export type SessionRecordKind =
  | 'message'
  | 'command'
  | 'file_change'
  | 'artifact'
  | 'question'
  | 'reasoning'
  | 'plan'
  | 'tool_call'
  | 'usage'
  | 'status';

export type SessionRecordActor = 'user' | 'agent' | 'system';
export type SessionRecordDriver = 'claude' | 'codex';
export type SessionRecordViewTier = 'lean' | 'full';

export interface SessionRecord {
  sessionId: string;
  eventId: number;
  seq: number;
  entryUid: string;
  kind: SessionRecordKind;
  actor: SessionRecordActor;
  driver: SessionRecordDriver | null;
  viewTier: SessionRecordViewTier;
  text: string;
  meta: JsonObject;
  ts: Date;
  /** Generated by Postgres; not produced by projectFrames before insert. */
  tsv?: string;
}

export interface ProjectFramesOptions {
  driver?: SessionRecordDriver;
  sessionId?: string;
  fallbackTs?: Date | string | number;
}

interface MutableProjectionState {
  sessionId: string;
  driver: SessionRecordDriver | null;
  fallbackTs: Date;
  records: SessionRecord[];
  dirtySeqs: Set<number>;
  openAmpTextIndex: number | null;
  toolRecordById: Map<string, number>;
  lastToolRecordIndex: number | null;
  questionRecordById: Map<string, number>;
  pendingUserMessageAuthor: JsonObject | null;
}

type RawFrameWithTs = CentaurEventFrame & {
  created_at?: Date | string;
  createdAt?: Date | string;
  ts?: Date | string | number;
  timestamp?: Date | string | number;
};

const REDACTED = '[redacted]';
const MAX_TEXT_EXCERPT = 4000;
const MAX_META_EXCERPT = 2000;
const ENTRY_UID_FALLBACK_ORDINAL_META = '__entryUidFallbackOrdinal';

const GOOGLE_API_KEY_RE = /\bAIza[A-Za-z0-9_-]{20,}\b/g;
const OPENAI_SECRET_RE = /\bsk-[A-Za-z0-9][A-Za-z0-9_-]{8,}\b/g;
const GITHUB_SECRET_RE = /\bgh[pousr]_[A-Za-z0-9_]{20,}\b/g;
const GITHUB_FINE_GRAINED_SECRET_RE = /\bgithub_pat_[A-Za-z0-9_]{20,}\b/g;
const SLACK_SECRET_RE = /\bxox[baprs]-[A-Za-z0-9-]{10,}\b/g;
const SLACK_APP_SECRET_RE = /\bxapp-[A-Za-z0-9-]{10,}\b/g;
const AWS_ACCESS_KEY_RE = /\b(?:AKIA|ASIA)[0-9A-Z]{16}\b/g;
const STRIPE_LIVE_SECRET_RE = /\b(?:sk|rk)_live_[A-Za-z0-9]{10,}\b/g;
const NPM_SECRET_RE = /\bnpm_[A-Za-z0-9]{20,}\b/g;
const GITLAB_PAT_RE = /\bglpat-[A-Za-z0-9_-]{20,}\b/g;
const JWT_RE = /\beyJ[A-Za-z0-9_-]{5,}\.[A-Za-z0-9_-]{5,}\.[A-Za-z0-9_-]{5,}\b/g;
const BEARER_RE = /\bBearer\s+[A-Za-z0-9._~+/=-]{10,}/gi;
const BASIC_AUTH_RE = /\b(Authorization\s*:\s*Basic\s+)[A-Za-z0-9._~+/=-]{8,}/gi;
const PRIVATE_KEY_RE =
  /-----BEGIN [A-Z0-9 ]*PRIVATE KEY-----[\s\S]*?-----END [A-Z0-9 ]*PRIVATE KEY-----/g;
const ASSIGNMENT_SECRET_RE =
  /\b(password|passwd|api[_-]?key|private[_-]?key|client[_-]?secret|secret|token|access[_-]?token|refresh[_-]?token)\b(\s*[:=]\s*)(["']?)([^\s"'`,;&]+)/gi;
const HEX_KEY_ASSIGNMENT_RE =
  /\b(private[_-]?key|secret|token|api[_-]?key|access[_-]?token)(\s*[:=]\s*)(["']?)0x[A-Fa-f0-9]{32,}\3/gi;
const HEX_ENTROPY_RE = /\b[A-Fa-f0-9]{32,}\b/g;
const BASE64_ENTROPY_RE = /\b[A-Za-z0-9+/_-]{40,}={0,2}\b/g;

// The session runner should call releaseSessionProjectionState when a session
// reaches a terminal state; until then this cache is bounded by active sessions.
const sessionProjectionStates = new Map<string, MutableProjectionState>();
const sessionProjectionLocks = new Map<string, Promise<unknown>>();

const CODEX_FILE_KIND: Record<string, 'add' | 'update' | 'delete'> = {
  add: 'add',
  create: 'add',
  created: 'add',
  added: 'add',
  update: 'update',
  modify: 'update',
  modified: 'update',
  edit: 'update',
  delete: 'delete',
  deleted: 'delete',
  remove: 'delete',
  removed: 'delete',
};

const SHELL_TOOL_NAMES = new Set([
  'bash',
  'shell',
  'terminal',
  'command',
  'run_shell_command',
]);

/**
 * Best-effort content scrubber for indexed/rendered text. It catches common
 * credential shapes (OpenAI/GitHub/Slack/AWS tokens, bearer tokens, JWTs,
 * private-key PEM blocks, and password/api_key/secret assignments) plus long
 * high-entropy base64/hex-looking strings. This is intentionally heuristic; it
 * reduces accidental indexing of secrets but is not a formal data-loss-prevention
 * guarantee.
 */
export function redactText(text: string): string {
  let out = text;
  out = out.replace(PRIVATE_KEY_RE, REDACTED);
  out = out.replace(BEARER_RE, `Bearer ${REDACTED}`);
  out = out.replace(BASIC_AUTH_RE, (_match, prefix: string) => `${prefix}${REDACTED}`);
  out = out.replace(
    HEX_KEY_ASSIGNMENT_RE,
    (_match, key: string, sep: string, quote: string) => `${key}${sep}${quote}${REDACTED}${quote}`,
  );
  out = out.replace(JWT_RE, REDACTED);
  out = out.replace(GOOGLE_API_KEY_RE, REDACTED);
  out = out.replace(OPENAI_SECRET_RE, REDACTED);
  out = out.replace(STRIPE_LIVE_SECRET_RE, REDACTED);
  out = out.replace(GITHUB_FINE_GRAINED_SECRET_RE, REDACTED);
  out = out.replace(GITHUB_SECRET_RE, REDACTED);
  out = out.replace(SLACK_SECRET_RE, REDACTED);
  out = out.replace(SLACK_APP_SECRET_RE, REDACTED);
  out = out.replace(AWS_ACCESS_KEY_RE, REDACTED);
  out = out.replace(NPM_SECRET_RE, REDACTED);
  out = out.replace(GITLAB_PAT_RE, REDACTED);
  out = out.replace(
    ASSIGNMENT_SECRET_RE,
    (_match, key: string, sep: string, quote: string) => `${key}${sep}${quote}${REDACTED}${quote}`,
  );
  out = redactEntropyMatches(out, HEX_ENTROPY_RE, 3.5);
  out = redactEntropyMatches(out, BASE64_ENTROPY_RE, 4.4);
  return out;
}

/**
 * Projection convention: each row is tagged with the lowest view tier that owns
 * it. Lean rows are implicitly part of the full transcript; a full transcript
 * should read both tiers, while `view_tier = 'full'` selects only full-only rows
 * such as reasoning, plan, and dynamic non-shell tool calls.
 */
export function projectFrames(
  frames: CentaurEventFrame[],
  opts: ProjectFramesOptions = {},
): SessionRecord[] {
  const state = createProjectionState(opts);

  for (const frame of frames) {
    projectFrame(state, frame);
  }

  return state.records;
}

export function releaseSessionProjectionState(sessionId: string): void {
  sessionProjectionStates.delete(sessionId);
}

export async function projectSessionIncremental(
  pool: Db,
  sessionId: string,
  opts: Omit<ProjectFramesOptions, 'sessionId'> = {},
): Promise<{ projected: number; total: number }> {
  return runSessionProjectionLocked(sessionId, () =>
    projectSessionIncrementalUnlocked(pool, sessionId, opts),
  );
}

export async function rebuildSessionRecords(
  pool: Db,
  sessionId: string,
  opts: Omit<ProjectFramesOptions, 'sessionId'> = {},
): Promise<number> {
  releaseSessionProjectionState(sessionId);
  try {
    return await withTx(pool, async (client) => {
      const rows = await client.query<{
        frame: CentaurEventFrame;
        centaur_event_id: number;
        created_at: Date;
      }>(
        `SELECT frame, centaur_event_id, created_at
         FROM session_events
         WHERE session_id = $1
         ORDER BY centaur_event_id ASC`,
        [sessionId],
      );
      const frames = rows.rows.map(
        (row) => ({ ...row.frame, created_at: row.created_at }) as RawFrameWithTs,
      ) as CentaurEventFrame[];
      const records = projectFrames(frames, { ...opts, sessionId });
      const maxEventId =
        rows.rows.length > 0 ? rows.rows[rows.rows.length - 1]!.centaur_event_id : null;

      await client.query('DELETE FROM session_records WHERE session_id = $1', [sessionId]);
      for (const record of records) {
        await insertSessionRecord(client, record);
      }
      if (maxEventId === null) {
        await client.query('DELETE FROM session_projection_state WHERE session_id = $1', [
          sessionId,
        ]);
      } else {
        await upsertProjectionCursor(client, sessionId, maxEventId);
      }
      return records.length;
    });
  } finally {
    releaseSessionProjectionState(sessionId);
  }
}

async function projectSessionIncrementalUnlocked(
  pool: Db,
  sessionId: string,
  opts: Omit<ProjectFramesOptions, 'sessionId'>,
): Promise<{ projected: number; total: number }> {
  let state: MutableProjectionState | null = null;
  try {
    const seeded = await getOrHydrateProjectionState(pool, sessionId, opts);
    state = seeded.state;
    const cursor = seeded.cursor;

    const rows = await pool.query<{
      frame: CentaurEventFrame;
      centaur_event_id: number;
      created_at: Date;
    }>(
      `SELECT frame, centaur_event_id, created_at
       FROM session_events
       WHERE session_id = $1
         AND centaur_event_id > $2
       ORDER BY centaur_event_id ASC`,
      [sessionId, cursor],
    );

    let maxEventId = cursor;
    for (const row of rows.rows) {
      maxEventId = row.centaur_event_id;
      projectFrame(state, { ...row.frame, created_at: row.created_at } as RawFrameWithTs);
    }

    const dirtySeqs = [...state.dirtySeqs].sort((a, b) => a - b);
    const projected = dirtySeqs.length;
    if (projected > 0 || maxEventId !== cursor) {
      await withTx(pool, async (client) => {
        for (const seq of dirtySeqs) {
          const record = state!.records[seq];
          if (record) await upsertSessionRecord(client, record);
        }
        if (maxEventId > 0) {
          await upsertProjectionCursor(client, sessionId, maxEventId);
        }
      });
      state.dirtySeqs.clear();
    }

    return { projected, total: state.records.length };
  } catch (err) {
    // Projection mutates the cached state before the DB write. If the write fails,
    // discard the cache so the next attempt hydrates from the durable cursor.
    releaseSessionProjectionState(sessionId);
    throw err;
  }
}

async function getOrHydrateProjectionState(
  pool: Db,
  sessionId: string,
  opts: Omit<ProjectFramesOptions, 'sessionId'>,
): Promise<{ state: MutableProjectionState; cursor: number }> {
  const cursor = await readProjectionCursor(pool, sessionId);
  const cached = sessionProjectionStates.get(sessionId);
  if (cached) {
    if (!cached.driver && opts.driver) cached.driver = opts.driver;
    return { state: cached, cursor };
  }

  const state = createProjectionState({ ...opts, sessionId });
  if (cursor > 0) {
    const rows = await pool.query<{ frame: CentaurEventFrame; created_at: Date }>(
      `SELECT frame, created_at
       FROM session_events
       WHERE session_id = $1
         AND centaur_event_id <= $2
       ORDER BY centaur_event_id ASC`,
      [sessionId, cursor],
    );
    for (const row of rows.rows) {
      projectFrame(state, { ...row.frame, created_at: row.created_at } as RawFrameWithTs);
    }
  }

  sessionProjectionStates.set(sessionId, state);
  return { state, cursor };
}

function createProjectionState(opts: ProjectFramesOptions = {}): MutableProjectionState {
  return {
    sessionId: opts.sessionId ?? '',
    driver: opts.driver ?? null,
    fallbackTs: coerceDate(opts.fallbackTs) ?? new Date(0),
    records: [],
    dirtySeqs: new Set(),
    openAmpTextIndex: null,
    toolRecordById: new Map(),
    lastToolRecordIndex: null,
    questionRecordById: new Map(),
    pendingUserMessageAuthor: null,
  };
}

async function runSessionProjectionLocked<T>(
  sessionId: string,
  fn: () => Promise<T>,
): Promise<T> {
  const previous = sessionProjectionLocks.get(sessionId) ?? Promise.resolve();
  const run = previous.catch(() => undefined).then(fn);
  sessionProjectionLocks.set(sessionId, run);
  try {
    return await run;
  } finally {
    if (sessionProjectionLocks.get(sessionId) === run) {
      sessionProjectionLocks.delete(sessionId);
    }
  }
}

async function readProjectionCursor(pool: Db, sessionId: string): Promise<number> {
  const row = await pool.query<{ last_event_id: number }>(
    `SELECT last_event_id
     FROM session_projection_state
     WHERE session_id = $1`,
    [sessionId],
  );
  return row.rows[0]?.last_event_id ?? 0;
}

async function insertSessionRecord(client: DbClient, record: SessionRecord): Promise<void> {
  await client.query(
    `INSERT INTO session_records
       (session_id, event_id, seq, entry_uid, kind, actor, driver, view_tier, text, meta, ts)
     VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)`,
    [
      record.sessionId,
      record.eventId,
      record.seq,
      record.entryUid,
      record.kind,
      record.actor,
      record.driver,
      record.viewTier,
      record.text,
      JSON.stringify(record.meta),
      record.ts,
    ],
  );
}

async function upsertSessionRecord(client: DbClient, record: SessionRecord): Promise<void> {
  await client.query(
    `INSERT INTO session_records
       (session_id, event_id, seq, entry_uid, kind, actor, driver, view_tier, text, meta, ts)
     VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
     ON CONFLICT (session_id, seq) DO UPDATE SET
       event_id = EXCLUDED.event_id,
       kind = EXCLUDED.kind,
       actor = EXCLUDED.actor,
       driver = EXCLUDED.driver,
       view_tier = EXCLUDED.view_tier,
       text = EXCLUDED.text,
       meta = EXCLUDED.meta,
       ts = EXCLUDED.ts`,
    [
      record.sessionId,
      record.eventId,
      record.seq,
      record.entryUid,
      record.kind,
      record.actor,
      record.driver,
      record.viewTier,
      record.text,
      JSON.stringify(record.meta),
      record.ts,
    ],
  );
}

async function upsertProjectionCursor(
  client: DbClient,
  sessionId: string,
  lastEventId: number,
): Promise<void> {
  await client.query(
    `INSERT INTO session_projection_state (session_id, last_event_id)
     VALUES ($1, $2)
     ON CONFLICT (session_id) DO UPDATE SET
       last_event_id = EXCLUDED.last_event_id,
       updated_at = now()`,
    [sessionId, lastEventId],
  );
}

function projectFrame(state: MutableProjectionState, frame: CentaurEventFrame): void {
  const ts = frameTs(frame, state.fallbackTs);
  const driver = inferDriver(state, frame);

  switch (frame.event) {
    case 'amp_raw_event':
      projectRawEvent(state, frame.event_id, normalizeRawEvent(frame.data), ts, driver);
      return;
    case 'artifact.captured':
      pushRecord(state, {
        eventId: frame.event_id,
        ts,
        kind: 'artifact',
        actor: 'agent',
        driver,
        viewTier: 'lean',
        text: renderArtifact(frame.data),
        meta: {
          artifactId: frame.data.artifact_id,
          executionId: frame.data.execution_id ?? null,
          path: displayPath(frame.data.path),
          kind: frame.data.kind,
          mime: frame.data.mime,
          sizeBytes: frame.data.size_bytes,
          sha256: frame.data.sha256,
          ref: frame.data.ref,
          sourceEventIds: [frame.event_id],
        },
      });
      return;
    case 'question_requested':
      upsertQuestionRecord(state, frame.event_id, ts, frame.data.question_id, {
        turnId: frame.data.turn_id,
        questions: frame.data.questions,
        status: 'pending',
      });
      return;
    case 'question_resolved':
      upsertQuestionRecord(state, frame.event_id, ts, frame.data.question_id, {
        questions: [],
        status: 'resolved',
        reason: frame.data.reason,
      });
      return;
    case 'usage_observed':
      pushRecord(state, {
        eventId: frame.event_id,
        ts,
        kind: 'usage',
        actor: 'system',
        driver,
        viewTier: 'lean',
        text: renderUsage(frame.data),
        meta: compactJsonObject({
          model: frame.data.model,
          costUsd: frame.data.cost_usd,
          inputTokens: frame.data.input_tokens,
          outputTokens: frame.data.output_tokens,
          totalTokens: frame.data.total_tokens,
          authoritative: frame.data.authoritative,
          sourceEventIds: [frame.event_id],
        }),
      });
      return;
    case 'execution_state':
      pushRecord(state, {
        eventId: frame.event_id,
        ts,
        kind: 'status',
        actor: 'system',
        driver,
        viewTier: 'lean',
        text: renderExecutionState(frame.data),
        meta: compactJsonObject({
          status: frame.data.status,
          threadKey: frame.data.thread_key,
          executionId: frame.data.execution_id,
          resultExcerpt:
            typeof frame.data.result_text === 'string'
              ? redactText(excerpt(frame.data.result_text, MAX_META_EXCERPT))
              : undefined,
          terminalReason: frame.data.terminal_reason,
          terminal: isTerminalExecutionStatus(frame.data.status),
          sourceEventIds: [frame.event_id],
        }),
      });
      return;
    case 'execution_summary':
      pushRecord(state, {
        eventId: frame.event_id,
        ts,
        kind: 'status',
        actor: 'system',
        driver,
        viewTier: 'lean',
        text: renderExecutionSummary(frame.data),
        meta: compactJsonObject({
          status: frame.data.status,
          models: frame.data.models,
          costUsd: frame.data.cost_usd,
          durationS: frame.data.duration_s,
          terminalReason: frame.data.terminal_reason,
          sourceEventIds: [frame.event_id],
        }),
      });
      return;
    case 'assistant_text_observed':
    case 'assistant_tool_use_observed':
    case 'tool_result_observed':
    case 'result_observed':
    case 'execution_started':
    case 'system_event_observed':
      return;
  }
}

function projectRawEvent(
  state: MutableProjectionState,
  eventId: number,
  raw: AmpRawEvent,
  ts: Date,
  driver: SessionRecordDriver | null,
): void {
  if (raw.type === 'assistant') {
    projectAmpAssistant(state, eventId, raw, ts, driver);
    return;
  }
  if (raw.type === 'tool') {
    projectAmpToolResult(state, eventId, raw, ts);
    return;
  }
  if (raw.type === 'item.completed') {
    projectCodexCompletedItem(state, eventId, raw.item, ts, driver);
  }
}

function projectAmpAssistant(
  state: MutableProjectionState,
  eventId: number,
  event: AmpAssistantEvent,
  ts: Date,
  driver: SessionRecordDriver | null,
): void {
  const reasoningText = event.message.content
    .filter(isReasoningBlock)
    .map(reasoningTextFromBlock)
    .filter(Boolean)
    .join('');
  const text = event.message.content
    .filter(isTextBlock)
    .map((block) => block.text)
    .join('');
  const toolBlocks = event.message.content.filter(isToolUseBlock);

  if (reasoningText) {
    pushRecord(state, {
      eventId,
      ts,
      kind: 'reasoning',
      actor: 'agent',
      driver,
      viewTier: 'full',
      text: reasoningText,
      meta: compactJsonObject({
        uuid: event.uuid,
        messageId: event.message.id,
        sourceEventIds: [eventId],
      }),
    });
  }

  if (text) {
    if (event.uuid) {
      if (state.openAmpTextIndex !== null) {
        updateRecord(state, state.openAmpTextIndex, {
          eventId,
          text,
          meta: mergeMeta(state.records[state.openAmpTextIndex]!.meta, {
            uuid: event.uuid,
            messageId: event.message.id,
            streaming: false,
            sourceEventIds: appendSourceEventId(
              state.records[state.openAmpTextIndex]!.meta,
              eventId,
            ),
          }),
        });
        state.openAmpTextIndex = null;
      } else {
        pushRecord(state, {
          eventId,
          ts,
          kind: 'message',
          actor: 'agent',
          driver,
          viewTier: 'lean',
          text,
          meta: compactJsonObject({
            uuid: event.uuid,
            messageId: event.message.id,
            sourceEventIds: [eventId],
          }),
        });
      }
    } else if (state.openAmpTextIndex !== null) {
      const existing = state.records[state.openAmpTextIndex]!;
      updateRecord(state, state.openAmpTextIndex, {
        text: `${existing.text}${text}`,
        meta: mergeMeta(existing.meta, {
          streaming: true,
          sourceEventIds: appendSourceEventId(existing.meta, eventId),
        }),
      });
    } else {
      state.openAmpTextIndex = pushRecord(state, {
        eventId,
        ts,
        kind: 'message',
        actor: 'agent',
        driver,
        viewTier: 'lean',
        text,
        meta: compactJsonObject({
          messageId: event.message.id,
          streaming: true,
          sourceEventIds: [eventId],
        }),
      });
    }
  }

  for (const block of toolBlocks) {
    projectToolUse(state, eventId, block, ts, driver);
  }
}

function projectToolUse(
  state: MutableProjectionState,
  eventId: number,
  block: AnthropicToolUseBlock,
  ts: Date,
  driver: SessionRecordDriver | null,
): void {
  const toolItem: ToolCallItem = {
    type: 'tool_call',
    id: block.id,
    name: block.name,
    input: block.input,
    sourceEventIds: [eventId],
  };
  const change = fileChangeFromToolCall(toolItem);

  let index: number;
  if (change) {
    index = pushRecord(state, {
      eventId,
      ts,
      kind: 'file_change',
      actor: 'agent',
      driver,
      viewTier: 'lean',
      text: renderFileChange(change.path, change.kind, change.diff),
      meta: compactJsonObject({
        toolName: change.toolName,
        toolUseId: block.id,
        path: change.path,
        kind: change.kind,
        diffExcerpt: redactText(excerpt(change.diff, MAX_META_EXCERPT)),
        sourceEventIds: [eventId],
      }),
    });
  } else if (isShellToolName(block.name)) {
    const command = commandFromInput(block.input) ?? stableJson(block.input);
    index = pushRecord(state, {
      eventId,
      ts,
      kind: 'command',
      actor: 'agent',
      driver,
      viewTier: 'lean',
      text: renderCommand(command),
      meta: compactJsonObject({
        toolName: block.name,
        toolUseId: block.id,
        command,
        argsExcerpt: redactText(excerpt(stableJson(block.input), MAX_META_EXCERPT)),
        sourceEventIds: [eventId],
      }),
    });
  } else {
    index = pushRecord(state, {
      eventId,
      ts,
      kind: 'tool_call',
      actor: 'agent',
      driver,
      viewTier: 'full',
      text: renderToolCall(block.name, block.input),
      meta: compactJsonObject({
        toolName: block.name,
        toolUseId: block.id,
        argsExcerpt: redactText(excerpt(stableJson(block.input), MAX_META_EXCERPT)),
        sourceEventIds: [eventId],
      }),
    });
  }

  state.toolRecordById.set(block.id, index);
  state.lastToolRecordIndex = index;
}

function projectAmpToolResult(
  state: MutableProjectionState,
  eventId: number,
  event: AmpToolEvent,
  _ts: Date,
): void {
  for (const result of event.content) {
    const index =
      (result.tool_use_id ? state.toolRecordById.get(result.tool_use_id) : undefined) ??
      state.lastToolRecordIndex;
    if (index === null || index === undefined) continue;
    const existing = state.records[index];
    if (!existing) continue;

    const resultExcerpt = excerpt(result.content, MAX_TEXT_EXCERPT);
    const meta = mergeMeta(existing.meta, {
      resultExcerpt: redactText(excerpt(result.content, MAX_META_EXCERPT)),
      isError: result.is_error,
      sourceEventIds: appendSourceEventId(existing.meta, eventId),
    });
    let text = existing.text;
    if (existing.kind === 'command') {
      text = renderCommand(stringFromMeta(meta, 'command') ?? 'command', resultExcerpt, undefined, result.is_error);
    } else if (existing.kind === 'tool_call') {
      text = renderToolCallWithExcerpt(
        stringFromMeta(meta, 'toolName') ?? 'tool',
        stringFromMeta(meta, 'argsExcerpt') ?? undefined,
        resultExcerpt,
        result.is_error,
      );
    }
    updateRecord(state, index, { meta, text });
  }
}

function projectCodexCompletedItem(
  state: MutableProjectionState,
  eventId: number,
  item: CodexItem,
  ts: Date,
  driver: SessionRecordDriver | null,
): void {
  if (item.type === 'userMessage') {
    const projected = projectUserMessageEcho(state, codexItemText(item));
    if (!projected) return;
    const { text, author } = projected;
    if (!text) return;
    pushRecord(state, {
      eventId,
      ts,
      kind: 'message',
      actor: 'user',
      driver,
      viewTier: 'lean',
      text,
      meta: compactJsonObject({ itemId: item.id, author, sourceEventIds: [eventId] }),
    });
    return;
  }

  if (item.type === 'agentMessage') {
    const text = codexItemText(item);
    if (!text) return;
    pushRecord(state, {
      eventId,
      ts,
      kind: 'message',
      actor: 'agent',
      driver,
      viewTier: 'lean',
      text,
      meta: compactJsonObject({ itemId: item.id, sourceEventIds: [eventId] }),
    });
    return;
  }

  if (item.type === 'commandExecution') {
    const command = codexCommandInput(item);
    const output = codexCommandOutput(item);
    const exitCode = codexExitCode(item);
    const status = stringField(item, 'status');
    pushRecord(state, {
      eventId,
      ts,
      kind: 'command',
      actor: 'agent',
      driver,
      viewTier: 'lean',
      text: renderCommand(command, output, exitCode, status ?? undefined),
      meta: compactJsonObject({
        itemId: item.id,
        command,
        exitCode,
        status,
        outputExcerpt: output ? redactText(excerpt(output, MAX_META_EXCERPT)) : undefined,
        sourceEventIds: [eventId],
      }),
    });
    return;
  }

  if (item.type === 'fileChange') {
    projectCodexFileChanges(state, eventId, item, ts, driver);
    return;
  }

  if (item.type === 'reasoning') {
    const text = codexItemTextOrJson(item);
    if (!text) return;
    pushRecord(state, {
      eventId,
      ts,
      kind: 'reasoning',
      actor: 'agent',
      driver,
      viewTier: 'full',
      text,
      meta: compactJsonObject({ itemId: item.id, sourceEventIds: [eventId] }),
    });
    return;
  }

  if (item.type === 'plan') {
    const text = codexItemTextOrJson(item);
    if (!text) return;
    pushRecord(state, {
      eventId,
      ts,
      kind: 'plan',
      actor: 'agent',
      driver,
      viewTier: 'full',
      text,
      meta: compactJsonObject({ itemId: item.id, sourceEventIds: [eventId] }),
    });
    return;
  }

  if (isLikelyDynamicToolItem(item)) {
    const toolName = codexToolName(item);
    const input = objectField(item, 'input') ?? objectField(item, 'args') ?? {};
    const output = codexCommandOutput(item);
    pushRecord(state, {
      eventId,
      ts,
      kind: isShellToolName(toolName) ? 'command' : 'tool_call',
      actor: 'agent',
      driver,
      viewTier: isShellToolName(toolName) ? 'lean' : 'full',
      text: isShellToolName(toolName)
        ? renderCommand(commandFromInput(input) ?? toolName, output)
        : renderToolCall(toolName, input, output),
      meta: compactJsonObject({
        itemId: item.id,
        toolName,
        argsExcerpt: redactText(excerpt(stableJson(input), MAX_META_EXCERPT)),
        resultExcerpt: output ? redactText(excerpt(output, MAX_META_EXCERPT)) : undefined,
        sourceEventIds: [eventId],
      }),
    });
  }
}

function projectCodexFileChanges(
  state: MutableProjectionState,
  eventId: number,
  item: CodexItem,
  ts: Date,
  driver: SessionRecordDriver | null,
): void {
  const changes = Array.isArray(item.changes) ? item.changes : [];
  changes.forEach((entry, idx) => {
    if (!isJsonObject(entry)) return;
    const path = stringField(entry, 'path');
    if (!path) return;
    const kindRaw = stringField(entry, 'kind')?.toLowerCase() ?? '';
    const kind = CODEX_FILE_KIND[kindRaw] ?? 'update';
    const diff = stringField(entry, 'diff') ?? '';
    const display = displayPath(path);
    pushRecord(state, {
      eventId,
      ts,
      kind: 'file_change',
      actor: 'agent',
      driver,
      viewTier: 'lean',
      text: renderFileChange(display, kind, diff),
      meta: compactJsonObject({
        itemId: item.id,
        changeIndex: idx,
        path: display,
        kind,
        diffExcerpt: diff ? redactText(excerpt(diff, MAX_META_EXCERPT)) : undefined,
        sourceEventIds: [eventId],
      }),
    });
  });
}

function upsertQuestionRecord(
  state: MutableProjectionState,
  eventId: number,
  ts: Date,
  questionId: string,
  update: {
    turnId?: string;
    questions: QuestionPrompt[];
    status: 'pending' | 'resolved';
    reason?: 'answered' | 'cancelled' | 'empty';
  },
): void {
  const existingIndex = state.questionRecordById.get(questionId);
  if (existingIndex !== undefined) {
    const existing = state.records[existingIndex]!;
    const existingQuestions = Array.isArray(existing.meta.questions)
      ? (existing.meta.questions as JsonValue[])
      : [];
    const questions =
      update.questions.length > 0
        ? sanitizeQuestions(update.questions)
        : existingQuestions;
    const meta = mergeMeta(existing.meta, {
      turnId: update.turnId ?? existing.meta.turnId,
      questions,
      status: update.status,
      reason: update.reason,
      sourceEventIds: appendSourceEventId(existing.meta, eventId),
    });
    updateRecord(state, existingIndex, {
      text: renderQuestion(questionId, questions, update.status, update.reason),
      meta,
    });
    return;
  }

  const questions = sanitizeQuestions(update.questions);
  const index = pushRecord(state, {
    eventId,
    ts,
    kind: 'question',
    actor: 'agent',
    driver: state.driver,
    viewTier: 'lean',
    text: renderQuestion(questionId, questions, update.status, update.reason),
    meta: compactJsonObject({
      questionId,
      turnId: update.turnId,
      questions,
      status: update.status,
      reason: update.reason,
      sourceEventIds: [eventId],
    }),
  });
  state.questionRecordById.set(questionId, index);
}

function pushRecord(
  state: MutableProjectionState,
  input: Omit<SessionRecord, 'sessionId' | 'seq' | 'entryUid' | 'text' | 'meta' | 'driver'> & {
    text: string;
    meta?: JsonObject;
    driver?: SessionRecordDriver | null;
  },
): number {
  const index = state.records.length;
  const rawMeta = input.meta ?? {};
  const meta = redactMeta(rawMeta);
  const { entryUid } = deriveEntryUid(
    {
      ...rawMeta,
      [ENTRY_UID_FALLBACK_ORDINAL_META]: fallbackOrdinalForSourceEvent(state, rawMeta),
    },
    input.kind,
  );
  state.records.push({
    sessionId: state.sessionId,
    eventId: input.eventId,
    seq: index,
    entryUid,
    kind: input.kind,
    actor: input.actor,
    driver: input.driver ?? state.driver,
    viewTier: input.viewTier,
    text: redactText(input.text),
    meta,
    ts: input.ts,
  });
  state.dirtySeqs.add(index);
  return index;
}

export type EntryUidSource = 'tu' | 'msg' | 'item' | 'q' | 'fb';

export function deriveEntryUid(
  meta: JsonObject,
  kind: SessionRecordKind,
): { entryUid: string; source: EntryUidSource } {
  const toolUseId = stringFromMeta(meta, 'tool_use_id') ?? stringFromMeta(meta, 'toolUseId');
  if (toolUseId) return entryUidFromRawKey('tu', toolUseId);

  const messageKey = stringFromMeta(meta, 'messageId') ?? stringFromMeta(meta, 'uuid');
  if (messageKey) {
    return entryUidFromRawKey('msg', kind === 'message' ? messageKey : `${kind}|${messageKey}`);
  }

  const itemId = stringFromMeta(meta, 'itemId');
  if (itemId) {
    const changeIndex = meta.changeIndex;
    const rawKey =
      typeof changeIndex === 'string' || typeof changeIndex === 'number'
        ? `change|${itemId}|${changeIndex}`
        : itemId;
    return entryUidFromRawKey('item', rawKey);
  }

  const questionId = stringFromMeta(meta, 'questionId');
  if (questionId) return entryUidFromRawKey('q', questionId);

  return entryUidFromRawKey(
    'fb',
    `${sourceEventKey(meta) ?? 'unknown'}|${kind}|${fallbackOrdinalFromMeta(meta)}`,
  );
}

function entryUidFromRawKey(
  source: EntryUidSource,
  rawKeyString: string,
): { entryUid: string; source: EntryUidSource } {
  const digest = createHash('sha256')
    .update(`${source}|${rawKeyString}`)
    .digest('hex')
    .slice(0, 24);
  return { entryUid: `${source}_${digest}`, source };
}

function fallbackOrdinalForSourceEvent(state: MutableProjectionState, meta: JsonObject): number {
  const key = sourceEventKey(meta);
  if (key === null) return 0;

  let ordinal = 0;
  for (const record of state.records) {
    if (sourceEventKey(record.meta) === key) ordinal += 1;
  }
  return ordinal;
}

function fallbackOrdinalFromMeta(meta: JsonObject): number {
  const ordinal = meta[ENTRY_UID_FALLBACK_ORDINAL_META];
  return typeof ordinal === 'number' && Number.isFinite(ordinal) ? ordinal : 0;
}

function sourceEventKey(meta: JsonObject): string | null {
  if (!Array.isArray(meta.sourceEventIds)) return null;
  const first = meta.sourceEventIds[0];
  if (typeof first !== 'string' && typeof first !== 'number') return null;
  return String(first);
}

function updateRecord(
  state: MutableProjectionState,
  index: number,
  updates: Partial<Pick<SessionRecord, 'eventId' | 'text' | 'meta'>>,
): void {
  const existing = state.records[index];
  if (!existing) return;
  state.records[index] = {
    ...existing,
    ...(updates.eventId !== undefined ? { eventId: updates.eventId } : {}),
    ...(updates.text !== undefined ? { text: redactText(updates.text) } : {}),
    ...(updates.meta !== undefined ? { meta: redactMeta(updates.meta) } : {}),
  };
  state.dirtySeqs.add(index);
}

function normalizeRawEvent(event: AmpRawEvent): AmpRawEvent {
  if (typeof event.type === 'string') return event;
  const raw = event as JsonObject;
  if (typeof raw.method !== 'string' || !isJsonObject(raw.params)) return event;
  const params = raw.params;
  switch (raw.method) {
    case 'item/started':
      return { type: 'item.started', ...params } as unknown as AmpRawEvent;
    case 'item/completed':
      return { type: 'item.completed', ...params } as unknown as AmpRawEvent;
    case 'item/agentMessage/delta':
      return {
        type: 'item.agentMessage.delta',
        ...params,
        itemId: stringValue(params.itemId) ?? stringValue(params.item_id),
      } as unknown as AmpRawEvent;
    case 'item/commandExecution/outputDelta':
      return {
        type: 'item.commandExecution.outputDelta',
        ...params,
        itemId: stringValue(params.itemId) ?? stringValue(params.item_id),
      } as unknown as AmpRawEvent;
    default:
      return event;
  }
}

function renderArtifact(data: Extract<CentaurEventFrame, { event: 'artifact.captured' }>['data']): string {
  return `Artifact ${data.kind}: ${displayPath(data.path)} (${data.mime}, ${data.size_bytes} bytes)`;
}

function renderUsage(data: Extract<CentaurEventFrame, { event: 'usage_observed' }>['data']): string {
  const parts = [`Usage: ${data.model}`];
  if (typeof data.cost_usd === 'number') parts.push(`cost $${data.cost_usd}`);
  if (typeof data.total_tokens === 'number') parts.push(`${data.total_tokens} tokens`);
  return parts.join(', ');
}

function renderExecutionState(data: Extract<CentaurEventFrame, { event: 'execution_state' }>['data']): string {
  const parts = [`Status: ${data.status}`];
  if (data.result_text) parts.push(`Result: ${excerpt(data.result_text, MAX_TEXT_EXCERPT)}`);
  if (data.terminal_reason) parts.push(`Reason: ${data.terminal_reason}`);
  return parts.join('\n');
}

function renderExecutionSummary(data: Extract<CentaurEventFrame, { event: 'execution_summary' }>['data']): string {
  const parts = [`Execution summary: ${data.status}`];
  if (data.models.length) parts.push(`models ${data.models.join(', ')}`);
  if (typeof data.cost_usd === 'number') parts.push(`cost $${data.cost_usd}`);
  if (typeof data.duration_s === 'number') parts.push(`duration ${data.duration_s}s`);
  if (data.terminal_reason) parts.push(`reason ${data.terminal_reason}`);
  return parts.join(', ');
}

function renderCommand(
  command: string,
  output?: string,
  exitCode?: number,
  statusOrError?: string | boolean,
): string {
  const lines = [`$ ${command}`];
  if (output) lines.push(excerpt(output, MAX_TEXT_EXCERPT));
  if (typeof exitCode === 'number') lines.push(`[exit ${exitCode}]`);
  if (typeof statusOrError === 'string' && statusOrError) lines.push(`[status ${statusOrError}]`);
  if (statusOrError === true) lines.push('[error]');
  return lines.join('\n');
}

function renderFileChange(path: string, kind: string, diff?: string): string {
  return [`File ${kind}: ${path}`, diff ? excerpt(diff, MAX_TEXT_EXCERPT) : ''].filter(Boolean).join('\n');
}

function renderToolCall(
  toolName: string,
  input?: JsonObject,
  result?: string,
  isError?: boolean,
): string {
  return renderToolCallWithExcerpt(
    toolName,
    input ? excerpt(stableJson(input), MAX_TEXT_EXCERPT) : undefined,
    result,
    isError,
  );
}

function renderToolCallWithExcerpt(
  toolName: string,
  argsExcerpt?: string,
  result?: string,
  isError?: boolean,
): string {
  const lines = [`Tool: ${toolName}`];
  if (argsExcerpt) lines.push(`Arguments: ${argsExcerpt}`);
  if (result) lines.push(`Result: ${excerpt(result, MAX_TEXT_EXCERPT)}`);
  if (isError) lines.push('[error]');
  return lines.join('\n');
}

function renderQuestion(
  questionId: string,
  questions: JsonValue[],
  status: 'pending' | 'resolved',
  reason?: string,
): string {
  const lines = [`Question ${questionId}: ${status}`];
  for (const question of questions) {
    if (!isJsonObject(question)) continue;
    const header = stringField(question, 'header');
    const prompt = stringField(question, 'question');
    if (header) lines.push(header);
    if (prompt) lines.push(prompt);
    const options = Array.isArray(question.options) ? question.options : [];
    for (const option of options) {
      if (!isJsonObject(option)) continue;
      const label = stringField(option, 'label');
      const description = stringField(option, 'description');
      if (label || description) lines.push(`- ${[label, description].filter(Boolean).join(': ')}`);
    }
  }
  if (reason) lines.push(`Resolved: ${reason}`);
  return lines.join('\n');
}

function codexItemText(item: CodexItem): string {
  if (typeof item.text === 'string') return item.text;
  return item.content
    ?.filter((content) => content.type === 'text')
    .map((content) => content.text)
    .join('') ?? '';
}

function codexItemTextOrJson(item: CodexItem): string {
  const text = codexItemText(item) || stringField(item, 'summary') || stringField(item, 'title');
  if (text) return text;
  return excerpt(stableJson(item as unknown as JsonObject), MAX_TEXT_EXCERPT);
}

function codexCommandInput(item: CodexItem): string {
  if (typeof item.command === 'string') return item.command;
  if (item.input) return commandFromInput(item.input) ?? stableJson(item.input);
  return 'command';
}

function codexCommandOutput(item: CodexItem): string {
  if (typeof item.output === 'string') return item.output;
  if (typeof item.stdout === 'string' || typeof item.stderr === 'string') {
    return [item.stdout, item.stderr]
      .filter((part): part is string => typeof part === 'string' && part.length > 0)
      .join('');
  }
  if (typeof item.text === 'string' && item.type !== 'agentMessage' && item.type !== 'userMessage') {
    return item.text;
  }
  return '';
}

function codexExitCode(item: CodexItem): number | undefined {
  if (typeof item.exit_code === 'number') return item.exit_code;
  if (typeof item.exitCode === 'number') return item.exitCode;
  return undefined;
}

function isLikelyDynamicToolItem(item: CodexItem): boolean {
  return (
    objectField(item, 'input') !== null ||
    objectField(item, 'args') !== null ||
    stringField(item, 'toolName') !== null ||
    stringField(item, 'tool_name') !== null ||
    stringField(item, 'name') !== null
  );
}

function codexToolName(item: CodexItem): string {
  return (
    stringField(item, 'toolName') ??
    stringField(item, 'tool_name') ??
    stringField(item, 'name') ??
    item.type
  );
}

function projectUserMessageEcho(
  state: MutableProjectionState,
  raw: string,
): { text: string; author?: JsonObject } | null {
  const prefixed = stripSteerContextPrefix(raw);
  if (prefixed && prefixed.text.length === 0) {
    state.pendingUserMessageAuthor = authorMetaFromContext(prefixed.context);
    return null;
  }

  const author = prefixed
    ? authorMetaFromContext(prefixed.context)
    : (state.pendingUserMessageAuthor ?? undefined);
  if (author) state.pendingUserMessageAuthor = null;

  return {
    text: stripInjectedContext(prefixed ? prefixed.text : raw),
    ...(author ? { author } : {}),
  };
}

function authorMetaFromContext(context: ParsedSteerContextBlock): JsonObject {
  return compactJsonObject({
    name: context.name,
    handle: context.handle ?? undefined,
    seat: context.seat ?? undefined,
  });
}

function stripInjectedContext(raw: string): string {
  let end = raw.length;
  for (const marker of ['\n# Session Context', '\n\n---\nReferenced entries:']) {
    const index = raw.indexOf(marker);
    if (index !== -1 && index < end) end = index;
  }
  return raw.slice(0, end);
}

function commandFromInput(input: JsonObject): string | null {
  return stringField(input, 'command') ?? stringField(input, 'cmd') ?? stringField(input, 'script');
}

function sanitizeQuestions(questions: QuestionPrompt[]): JsonValue[] {
  return questions.map((question) =>
    compactJsonObject({
      id: question.id,
      header: question.header,
      question: question.question,
      multiSelect: question.multiSelect,
      isOther: question.isOther,
      isSecret: question.isSecret,
      options: question.options?.map((option) =>
        compactJsonObject({
          label: option.label,
          description: option.description,
        }),
      ),
    }),
  );
}

function inferDriver(
  state: MutableProjectionState,
  frame: CentaurEventFrame,
): SessionRecordDriver | null {
  if (state.driver) return state.driver;
  const harness = isJsonObject(frame.data) ? stringField(frame.data, 'harness') : null;
  if (harness === 'claude' || harness === 'codex') return harness;
  const engine = isJsonObject(frame.data) ? stringField(frame.data, 'engine') : null;
  if (engine === 'claude' || engine === 'codex') return engine;
  return null;
}

function frameTs(frame: CentaurEventFrame, fallback: Date): Date {
  const raw = frame as RawFrameWithTs;
  return (
    coerceDate(raw.ts) ??
    coerceDate(raw.timestamp) ??
    coerceDate(raw.created_at) ??
    coerceDate(raw.createdAt) ??
    (isJsonObject(frame.data)
      ? coerceDate(frame.data.ts) ??
        coerceDate(frame.data.timestamp) ??
        coerceDate(frame.data.created_at) ??
        coerceDate(frame.data.createdAt)
      : null) ??
    fallback
  );
}

function coerceDate(value: unknown): Date | null {
  if (value instanceof Date) return Number.isNaN(value.getTime()) ? null : value;
  if (typeof value !== 'string' && typeof value !== 'number') return null;
  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? null : date;
}

function redactMeta(meta: JsonObject): JsonObject {
  const out: JsonObject = {};
  for (const [key, value] of Object.entries(meta)) {
    if (value === undefined) continue;
    out[key] = redactJsonValue(value);
  }
  return out;
}

function redactJsonValue(value: unknown): JsonValue {
  if (typeof value === 'string') return redactText(value);
  if (typeof value === 'number' || typeof value === 'boolean' || value === null) return value;
  if (value instanceof Date) return value.toISOString();
  if (Array.isArray(value)) return value.map((entry) => redactJsonValue(entry));
  if (isJsonObject(value)) return redactMeta(value);
  return String(value);
}

function compactJsonObject(input: Record<string, unknown>): JsonObject {
  const out: JsonObject = {};
  for (const [key, value] of Object.entries(input)) {
    if (value !== undefined) out[key] = value;
  }
  return out;
}

function mergeMeta(base: JsonObject, update: Record<string, unknown>): JsonObject {
  return compactJsonObject({ ...base, ...update });
}

function appendSourceEventId(meta: JsonObject, eventId: number): number[] {
  const existing = Array.isArray(meta.sourceEventIds)
    ? meta.sourceEventIds.filter((value): value is number => typeof value === 'number')
    : [];
  return existing.includes(eventId) ? existing : [...existing, eventId];
}

function stringFromMeta(meta: JsonObject, key: string): string | null {
  const value = meta[key];
  return typeof value === 'string' ? value : null;
}

function objectField(value: JsonObject, key: string): JsonObject | null {
  const field = value[key];
  return isJsonObject(field) ? field : null;
}

function stringField(value: JsonObject, key: string): string | null {
  const field = value[key];
  return typeof field === 'string' ? field : null;
}

function isShellToolName(name: string): boolean {
  return SHELL_TOOL_NAMES.has(name.toLowerCase());
}

function isTextBlock(block: { type: string }): block is { type: 'text'; text: string } {
  return block.type === 'text' && typeof (block as { text?: unknown }).text === 'string';
}

function isReasoningBlock(block: { type: string }): block is { type: string } & JsonObject {
  return block.type === 'thinking' || block.type === 'reasoning';
}

function reasoningTextFromBlock(block: { type: string } & JsonObject): string {
  return stringField(block, 'thinking') ?? stringField(block, 'text') ?? '';
}

function isToolUseBlock(block: { type: string }): block is AnthropicToolUseBlock {
  return block.type === 'tool_use';
}

function isJsonObject(value: unknown): value is JsonObject {
  return value !== null && typeof value === 'object' && !Array.isArray(value);
}

function stringValue(value: unknown): string | undefined {
  return typeof value === 'string' ? value : undefined;
}

function stableJson(value: JsonObject): string {
  return JSON.stringify(value, null, 2);
}

function excerpt(text: string, max: number): string {
  if (text.length <= max) return text;
  return `${text.slice(0, max)}\n[truncated]`;
}

function redactEntropyMatches(text: string, pattern: RegExp, minEntropy: number): string {
  return text.replace(pattern, (candidate) => {
    if (/^0x[A-Fa-f0-9]{32,}$/i.test(candidate)) return candidate;
    const normalized = candidate.replace(/=+$/g, '');
    return shannonEntropy(normalized) >= minEntropy ? REDACTED : candidate;
  });
}

function shannonEntropy(value: string): number {
  if (!value) return 0;
  const counts = new Map<string, number>();
  for (const ch of value) counts.set(ch, (counts.get(ch) ?? 0) + 1);
  let entropy = 0;
  for (const count of counts.values()) {
    const p = count / value.length;
    entropy -= p * Math.log2(p);
  }
  return entropy;
}
