export const webPalette = {
  dark: {
    surface: '#09090b',
    'surface-raised': '#18181b',
    'surface-overlay': '#27272a',
    edge: '#27272a',
    'edge-strong': '#3f3f46',
    'edge-hover': '#52525b',
    'edge-focus': '#71717a',
    fg: '#f4f4f5',
    'fg-body': '#e4e4e7',
    'fg-secondary': '#d4d4d8',
    'fg-tertiary': '#a1a1aa',
    'fg-muted': '#8f8f98',
    'fg-faint': '#85858e',
    accent: '#4f46e5',
    'accent-hover': '#6366f1',
    'accent-text': '#818cf8',
    'accent-text-strong': '#a5b4fc',
    'accent-border': '#4338ca',
    'accent-border-muted': '#3730a3',
    'accent-tint': '#312e81',
    'on-accent': '#ffffff',
    danger: '#f87171',
    'danger-strong': '#dc2626',
    'danger-text': '#fca5a5',
    'danger-text-strong': '#fecaca',
    'danger-border': '#7f1d1d',
    'danger-border-strong': '#b91c1c',
    'danger-tint': '#450a0a',
    'danger-surface': '#7f1d1d',
    warning: '#f59e0b',
    'warning-hover': '#fbbf24',
    'warning-text': '#fcd34d',
    'warning-text-strong': '#fef3c7',
    'warning-border': '#78350f',
    'warning-tint': '#451a03',
    success: '#10b981',
    'success-text': '#6ee7b7',
    info: '#0ea5e9',
    'info-text': '#7dd3fc',
    code: '#fda4af',
  },
  light: {
    surface: '#fafafa',
    'surface-raised': '#fdfdff',
    'surface-overlay': '#f4f4f5',
    edge: '#d4d4d8',
    'edge-strong': '#a1a1aa',
    'edge-hover': '#71717a',
    'edge-focus': '#52525b',
    fg: '#18181b',
    'fg-body': '#27272a',
    'fg-secondary': '#3f3f46',
    'fg-tertiary': '#52525b',
    'fg-muted': '#52525b',
    'fg-faint': '#a1a1aa',
    accent: '#4f46e5',
    'accent-hover': '#4338ca',
    'accent-text': '#4338ca',
    'accent-text-strong': '#3730a3',
    'accent-border': '#6366f1',
    'accent-border-muted': '#c7d2fe',
    'accent-tint': '#e0e7ff',
    'on-accent': '#ffffff',
    danger: '#dc2626',
    'danger-strong': '#b91c1c',
    'danger-text': '#b91c1c',
    'danger-text-strong': '#991b1b',
    'danger-border': '#fca5a5',
    'danger-border-strong': '#dc2626',
    'danger-tint': '#fecaca',
    'danger-surface': '#fee2e2',
    warning: '#d97706',
    'warning-hover': '#b45309',
    'warning-text': '#92400e',
    'warning-text-strong': '#78350f',
    'warning-border': '#fcd34d',
    'warning-tint': '#fde68a',
    success: '#059669',
    'success-text': '#047857',
    info: '#0284c7',
    'info-text': '#0369a1',
    code: '#be123c',
  },
  accents: {
    teal: {
      dark: {
        accent: '#0d9488',
        'accent-hover': '#14b8a6',
        'accent-text': '#5eead4',
        'accent-text-strong': '#99f6e4',
        'accent-border': '#0f766e',
        'accent-border-muted': '#115e59',
        'accent-tint': '#134e4a',
        'on-accent': '#18181b',
      },
      light: {
        accent: '#0d9488',
        'accent-hover': '#0f766e',
        'accent-text': '#0f766e',
        'accent-text-strong': '#115e59',
        'accent-border': '#14b8a6',
        'accent-border-muted': '#99f6e4',
        'accent-tint': '#ccfbf1',
        'on-accent': '#18181b',
      },
    },
    amber: {
      dark: {
        accent: '#f59e0b',
        'accent-hover': '#fbbf24',
        'accent-text': '#fcd34d',
        'accent-text-strong': '#fef3c7',
        'accent-border': '#b45309',
        'accent-border-muted': '#92400e',
        'accent-tint': '#451a03',
        'on-accent': '#18181b',
      },
      light: {
        accent: '#d97706',
        'accent-hover': '#b45309',
        'accent-text': '#92400e',
        'accent-text-strong': '#78350f',
        'accent-border': '#f59e0b',
        'accent-border-muted': '#fde68a',
        'accent-tint': '#fef3c7',
        'on-accent': '#18181b',
      },
    },
    rose: {
      dark: {
        accent: '#e11d48',
        'accent-hover': '#f43f5e',
        'accent-text': '#fb7185',
        'accent-text-strong': '#fda4af',
        'accent-border': '#be123c',
        'accent-border-muted': '#9f1239',
        'accent-tint': '#4c0519',
        'on-accent': '#ffffff',
      },
      light: {
        accent: '#e11d48',
        'accent-hover': '#be123c',
        'accent-text': '#be123c',
        'accent-text-strong': '#9f1239',
        'accent-border': '#f43f5e',
        'accent-border-muted': '#fecdd3',
        'accent-tint': '#ffe4e6',
        'on-accent': '#ffffff',
      },
    },
  },
  highContrast: {
    dark: {
      'fg-muted': '#a1a1aa',
      'fg-faint': '#8f8f98',
      edge: '#3f3f46',
      'edge-strong': '#52525b',
    },
    light: {
      'fg-muted': '#52525b',
      'fg-faint': '#52525b',
      edge: '#a1a1aa',
      'edge-strong': '#71717a',
    },
  },
} as const;

/**
 * A `webPalette` reference below means the mobile value is intentionally the
 * same design token as web. Values that merely coincide with a web hex stay
 * literal so the surfaces can diverge without silent side effects.
 */
export const mobilePalette = {
  schemeTokens: {
    dark: {
      bg: webPalette.dark.surface,
      bgElevated: webPalette.dark['surface-raised'],
      bgInput: '#1f1f23',
      bgPressed: webPalette.dark['surface-overlay'],
      border: webPalette.dark.edge,
      borderSoft: '#1c1c20',
      text: webPalette.dark.fg,
      textSecondary: webPalette.dark['fg-tertiary'],
      textMuted: webPalette.dark['fg-muted'],
      textFaint: webPalette.dark['fg-faint'],
      mention: webPalette.dark['danger-strong'],
      onMention: webPalette.dark['on-accent'],
      danger: webPalette.dark.danger,
      dangerSurface: 'rgba(127, 29, 29, 0.22)',
      dangerBorder: 'rgba(248, 113, 113, 0.55)',
      warning: webPalette.dark['warning-hover'],
      warningSurface: 'rgba(120, 53, 15, 0.3)',
      warningBorder: 'rgba(146, 64, 14, 0.4)',
      online: '#34d399',
      codeAccent: webPalette.dark.code,
      scrim: 'rgba(0, 0, 0, 0.55)',
      letterbox: '#000000',
      switchTrackOff: webPalette.dark['edge-strong'],
      switchThumbOff: '#d4d4d8',
    },
    light: {
      bg: webPalette.light.surface,
      bgElevated: '#ffffff',
      bgInput: '#ffffff',
      bgPressed: '#e4e4e7',
      border: webPalette.light.edge,
      borderSoft: '#e4e4e7',
      text: webPalette.light.fg,
      textSecondary: webPalette.light['fg-secondary'],
      textMuted: webPalette.light['fg-muted'],
      textFaint: '#71717a',
      mention: webPalette.light.danger,
      onMention: webPalette.light['on-accent'],
      danger: webPalette.light.danger,
      dangerSurface: 'rgba(254, 226, 226, 0.92)',
      dangerBorder: 'rgba(220, 38, 38, 0.5)',
      warning: webPalette.light['warning-hover'],
      warningSurface: 'rgba(254, 243, 199, 0.9)',
      warningBorder: 'rgba(180, 83, 9, 0.42)',
      online: webPalette.light['success-text'],
      codeAccent: webPalette.light.code,
      scrim: 'rgba(0, 0, 0, 0.45)',
      letterbox: '#000000',
      switchTrackOff: webPalette.light.edge,
      switchThumbOff: '#ffffff',
    },
  },
  accents: {
    dark: {
      indigo: {
        accent: webPalette.dark['accent-text'],
        accentBg: 'rgba(129, 140, 248, 0.16)',
        onAccent: webPalette.dark.surface,
      },
      teal: { accent: '#2dd4bf', accentBg: 'rgba(45, 212, 191, 0.14)', onAccent: webPalette.dark.surface },
      amber: {
        accent: webPalette.accents.amber.dark['accent-hover'],
        accentBg: 'rgba(251, 191, 36, 0.14)',
        onAccent: webPalette.dark.surface,
      },
      rose: {
        accent: webPalette.accents.rose.dark['accent-text'],
        accentBg: 'rgba(251, 113, 133, 0.16)',
        onAccent: webPalette.dark.surface,
      },
    },
    light: {
      indigo: {
        accent: webPalette.light.accent,
        accentBg: 'rgba(79, 70, 229, 0.11)',
        onAccent: webPalette.light['on-accent'],
      },
      teal: {
        accent: webPalette.accents.teal.light['accent-text'],
        accentBg: 'rgba(15, 118, 110, 0.1)',
        onAccent: webPalette.light['on-accent'],
      },
      amber: {
        accent: webPalette.accents.amber.light['accent-hover'],
        accentBg: 'rgba(180, 83, 9, 0.11)',
        onAccent: webPalette.light['on-accent'],
      },
      rose: {
        accent: webPalette.accents.rose.light['accent-text'],
        accentBg: 'rgba(190, 18, 60, 0.1)',
        onAccent: webPalette.light['on-accent'],
      },
    },
  },
  highContrast: {
    dark: {
      textMuted: webPalette.highContrast.dark['fg-muted'],
      textFaint: '#71717a',
      border: '#71717a',
      borderSoft: webPalette.highContrast.dark['edge-strong'],
    },
    light: {
      textMuted: webPalette.light['fg-secondary'],
      textFaint: webPalette.highContrast.light['fg-faint'],
      border: webPalette.highContrast.light['edge-strong'],
      borderSoft: webPalette.highContrast.light['edge-strong'],
    },
  },
} as const;
